# Generated by Django 5.2.7 on 2025-11-10 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_code', models.CharField(choices=[('missing', 'missing'), ('report', 'report'), ('tip', 'tip')], db_index=True, max_length=10)),
                ('occr_date', models.DateTimeField(blank=True, help_text='발생 일시', null=True)),
                ('occr_location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('found', 'found'), ('pending', 'pending'), ('closed', 'closed')], db_index=True, default='active', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothing', models.TextField(blank=True, null=True)),
                ('physical', models.TextField(blank=True, null=True)),
                ('health', models.TextField(blank=True, null=True)),
                ('behavior', models.TextField(blank=True, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
                ('ai_source', models.CharField(choices=[('rule', 'rule'), ('kobert', 'kobert'), ('manual', 'manual')], default='manual', max_length=10)),
                ('confidence', models.FloatField(default=0.0, help_text='0.0~1.0 (명세에 % 기재 있으나 서비스단에서 변환 추천)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='dasibomapp.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Montage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_img', models.CharField(max_length=255)),
                ('result_img', models.CharField(max_length=255)),
                ('age_estimate', models.IntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montages', to='dasibomapp.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='사용자 이름', max_length=255, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default='unknown', max_length=8)),
                ('birth', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('guardian', 'guardian'), ('citizen', 'citizen'), ('missing', 'missing'), ('child', 'child')], db_index=True, default='citizen', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('health_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='dasibomapp__role_5d38be_idx'), models.Index(fields=['name'], name='dasibomapp__name_e2e127_idx'), models.Index(fields=['phone'], name='dasibomapp__phone_808ebc_idx')],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='person',
            field=models.ForeignKey(blank=True, help_text='관련 인물(실종자 등)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_cases', to='dasibomapp.person'),
        ),
        migrations.AddField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='신고자/제보자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to='dasibomapp.person'),
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, help_text='해시 저장. OAuth 계정은 NULL 가능', max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('guardian', 'guardian'), ('citizen', 'citizen'), ('guest', 'guest')], default='citizen', max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='세션/디바이스 식별자', max_length=100, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='dasibomapp.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('case', 'case'), ('user', 'user'), ('device', 'device'), ('ai', 'ai'), ('system', 'system')], max_length=10)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dasibomapp.person')),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='dasibomapp__target__a888d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('voice_call', 'voice_call'), ('video_call', 'video_call'), ('alert', 'alert'), ('nfc_tag', 'nfc_tag')], db_index=True, max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, choices=[('success', 'success'), ('missed', 'missed'), ('failed', 'failed')], max_length=10, null=True)),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_interactions', to='dasibomapp.person')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_interactions', to='dasibomapp.person')),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'start_time'], name='dasibomapp__type_93bb71_idx'), models.Index(fields=['from_person', 'to_person'], name='dasibomapp__from_pe_900dac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(blank=True, max_length=30, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='dasibomapp.person')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='dasibomapp.person')),
            ],
            options={
                'indexes': [models.Index(fields=['guardian'], name='dasibomapp__guardia_bebed6_idx'), models.Index(fields=['ward'], name='dasibomapp__ward_id_bd07ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('guardian', 'ward'), name='uniq_guardian_ward')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_uid', models.CharField(help_text='하드웨어 고유 식별 코드', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('error', 'error'), ('disconnected', 'disconnected')], db_index=True, default='inactive', max_length=12)),
                ('battery', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_signal_time', models.DateTimeField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nfc_tag', models.BooleanField(default=False, help_text='True면 보호자 착신/알림 트리거')),
                ('signal_strength', models.IntegerField(blank=True, help_text='BLE 신호 세기 (RSSI)', null=True)),
                ('person', models.ForeignKey(help_text='소유자(보통 피보호자)', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dasibomapp.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person'], name='dasibomapp__person__75003c_idx'), models.Index(fields=['status'], name='dasibomapp__status_6e8a7c_idx'), models.Index(fields=['last_signal_time'], name='dasibomapp__last_si_8c16c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['type_code', 'status'], name='dasibomapp__type_co_0f1223_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['occr_date'], name='dasibomapp__occr_da_e07218_idx'),
        ),
    ]
