# Generated by Django 5.2.7 on 2025-11-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('missing_date', models.DateField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
