# Generated by Django 5.2.7 on 2025-11-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0002_missingperson_phoneverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
        migrations.AddField(
            model_name='userauth',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
