# Generated by Django 5.2.7 on 2025-11-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0003_delete_phoneverification_userauth_firebase_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='dasibomapp__date_f63361_idx')],
            },
        ),
    ]
