# Generated by Django 5.2.7 on 2025-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0004_phonelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='dasibomapp__created_759f5c_idx')],
            },
        ),
    ]
