# Generated by Django 5.2.7 on 2025-11-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0005_phonerequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phonerequest',
            index=models.Index(fields=['phone'], name='dasibomapp__phone_b8adba_idx'),
        ),
    ]
