# Generated by Django 5.2.7 on 2026-01-24 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0013_remove_missingperson_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingperson',
            options={'verbose_name': '실종자', 'verbose_name_plural': '실종자 목록'},
        ),
        migrations.AlterModelOptions(
            name='missingpersonphoto',
            options={'verbose_name': '실종자 사진', 'verbose_name_plural': '실종자 사진'},
        ),
        migrations.RenameField(
            model_name='missingperson',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingperson',
            name='source',
            field=models.CharField(db_index=True, default='safe182', help_text='데이터 출처 (safe182, manual, ai)', max_length=20),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='address',
            field=models.CharField(blank=True, help_text='실종 발생 장소', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='age',
            field=models.CharField(blank=True, help_text='실종 당시 나이 (문자열 유지)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='clothes',
            field=models.CharField(blank=True, help_text='실종 당시 인상착의', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='current_age',
            field=models.IntegerField(blank=True, help_text='현재 추정 나이', null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='detail',
            field=models.TextField(blank=True, help_text='기타 특이사항', null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='missing_date',
            field=models.DateField(blank=True, help_text='실종 발생 일자', null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='seq',
            field=models.CharField(help_text='Safe182 childSeq (외부 API 고유 ID)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(blank=True, help_text='진행 상태 (접수, 발견, 종료 등)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='missingpersonphoto',
            name='is_main',
            field=models.BooleanField(default=False, help_text='대표 사진 여부'),
        ),
        migrations.AlterField(
            model_name='missingpersonphoto',
            name='photo_url',
            field=models.URLField(help_text='실종자 사진 URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['seq'], name='dasibomapp__seq_ddd475_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['status'], name='dasibomapp__status_fa629a_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['missing_date'], name='dasibomapp__missing_4b0dea_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['source'], name='dasibomapp__source_15f6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpersonphoto',
            index=models.Index(fields=['person', 'is_main'], name='dasibomapp__person__50abb4_idx'),
        ),
    ]
