# Generated by Django 5.2.7 on 2026-01-24 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0014_alter_missingperson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpersonphoto',
            name='person',
            field=models.ForeignKey(help_text='연결된 실종자', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dasibomapp.missingperson'),
        ),
        migrations.AlterField(
            model_name='missingpersonphoto',
            name='photo_url',
            field=models.TextField(help_text='실종자 사진 URL (Safe182 제공, 길이 제한 없음)'),
        ),
    ]
