# Generated by Django 5.2.7 on 2026-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0015_alter_missingpersonphoto_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='ai_behaviors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='AI 분석 신뢰도 (0~1)', null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='ai_diseases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='ai_risk_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, help_text='AI 추정 위험도', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='parsed_cane',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='parsed_glasses',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='parsed_hair_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='parsed_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='parsed_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='age',
            field=models.CharField(blank=True, help_text='실종 당시 나이 (문자열 그대로 유지)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='detail',
            field=models.TextField(blank=True, help_text='기타 특이사항 (자연어 원문)', null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='seq',
            field=models.CharField(help_text='Safe182 고유 식별자 (예: safe182-1-20260121)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='source',
            field=models.CharField(db_index=True, default='safe182', help_text='데이터 출처 (safe182 / manual / ai)', max_length=20),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(blank=True, help_text='진행 상태 코드', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='montage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='montage',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['ai_risk_level'], name='dasibomapp__ai_risk_d37b9f_idx'),
        ),
    ]
