# Generated by Django 5.2.7 on 2026-01-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0016_missingperson_ai_behaviors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='kobert_confidence',
            field=models.JSONField(blank=True, help_text='각 분류 라벨별 신뢰도', null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='kobert_labels',
            field=models.JSONField(blank=True, help_text='KoBERT 기반 의미 분류 결과 (health/behavior/risk_context)', null=True),
        ),
    ]
