# Generated by Django 5.2.7 on 2026-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0017_missingperson_kobert_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingpersonphoto',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='missingpersonphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='missing/'),
        ),
    ]
