# Generated by Django 5.2.7 on 2026-02-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0018_remove_missingpersonphoto_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='dasibomapp.missingperson'),
        ),
    ]
