# Generated by Django 5.2.7 on 2026-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0019_case_missing_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reported_missing_name',
            field=models.CharField(blank=True, help_text='제보자가 입력한 실종자 이름 (원본 보존)', max_length=100, null=True),
        ),
    ]
