# Generated by Django 5.2.7 on 2026-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0020_case_reported_missing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='occr_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', '접수중'), ('reviewing', '확인중'), ('completed', '제보 완료')], db_index=True, default='received', max_length=20),
        ),
    ]
