# Generated by Django 5.2.7 on 2026-03-03 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0021_alter_case_occr_date_alter_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='cases/')),
                ('is_main', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dasibomapp.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
