# Generated by Django 5.2.7 on 2026-03-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0022_casephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontageInputPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='montage/input/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='dasibomapp__type_co_0f1223_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='dasibomapp__occr_da_e07218_idx',
        ),
        migrations.RemoveField(
            model_name='montage',
            name='case',
        ),
        migrations.RemoveField(
            model_name='montage',
            name='input_img',
        ),
        migrations.AddField(
            model_name='montage',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_montages', to='dasibomapp.person'),
        ),
        migrations.AddField(
            model_name='montage',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='montage',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montages', to='dasibomapp.missingperson'),
        ),
        migrations.AlterField(
            model_name='case',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_cases', to='dasibomapp.person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reported_missing_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to='dasibomapp.person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', '접수중'), ('reviewing', '확인중'), ('completed', '완료')], db_index=True, default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_code',
            field=models.CharField(choices=[('missing', 'missing'), ('report', 'report'), ('tip', 'tip'), ('montage', 'montage')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='montage',
            name='result_img',
            field=models.ImageField(upload_to='montage/result/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('guardian', 'guardian'), ('citizen', 'citizen')], db_index=True, default='citizen', max_length=10),
        ),
        migrations.AddField(
            model_name='montageinputphoto',
            name='montage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_photos', to='dasibomapp.montage'),
        ),
    ]
