# Generated by Django 5.2.7 on 2026-03-10 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0023_montageinputphoto_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='dasibomapp__role_5d38be_idx',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
