# Generated by Django 5.2.7 on 2026-03-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0024_remove_person_dasibomapp__role_5d38be_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CasePhoto',
        ),
    ]
