# Generated by Django 5.2.7 on 2026-03-17 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0026_protectedperson_protectedpersonphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protectedperson',
            options={'ordering': ['-occurred_at'], 'verbose_name': '보호중 실종자', 'verbose_name_plural': '보호중 실종자 목록'},
        ),
        migrations.RemoveField(
            model_name='protectedperson',
            name='age',
        ),
        migrations.RemoveField(
            model_name='protectedperson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='protectedperson',
            name='hair_type',
        ),
        migrations.RemoveField(
            model_name='protectedperson',
            name='missing_date',
        ),
        migrations.RemoveField(
            model_name='protectedperson',
            name='missing_location',
        ),
        migrations.RemoveField(
            model_name='protectedperson',
            name='seq',
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='age_at_missing',
            field=models.IntegerField(blank=True, null=True, verbose_name='당시나이(세)'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='category',
            field=models.CharField(blank=True, default='', help_text='아동, 장애, 치매환자, 가출인 등', max_length=20, verbose_name='분류'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='crawled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='크롤링일시'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='current_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='현재나이(세)'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='hair_style',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='두발형태'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='이미지URL목록'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='msspsn_idntfccd',
            field=models.CharField(default='', help_text='safe182 고유 식별코드 (예: 5647061)', max_length=20, unique=True, verbose_name='실종자식별코드'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='국적'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='occurred_at',
            field=models.DateField(blank=True, null=True, verbose_name='발생일시'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='occurred_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='발생장소'),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='체격'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='clothing',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='착의의상'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='face_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='얼굴형'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('남자', '남자'), ('여자', '여자')], default='', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='hair_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='두발색상'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='height',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='진행상태'),
        ),
        migrations.AlterField(
            model_name='protectedperson',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='몸무게'),
        ),
        migrations.AlterModelTable(
            name='protectedperson',
            table='safe182_protected_person',
        ),
    ]
