# Generated by Django 5.2.7 on 2026-03-18 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0027_alter_protectedperson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingpersonphoto',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='missingperson',
            options={'ordering': ['-occurred_at'], 'verbose_name': '실종자', 'verbose_name_plural': '실종자 목록'},
        ),
        migrations.RemoveIndex(
            model_name='missingperson',
            name='dasibomapp__seq_ddd475_idx',
        ),
        migrations.RemoveIndex(
            model_name='missingperson',
            name='dasibomapp__missing_4b0dea_idx',
        ),
        migrations.RemoveIndex(
            model_name='missingperson',
            name='dasibomapp__source_15f6cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='missingperson',
            name='dasibomapp__ai_risk_d37b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='missingperson',
            new_name='safe182_mis_status_69f081_idx',
            old_name='dasibomapp__status_fa629a_idx',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='age',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='ai_behaviors',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='ai_diseases',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='ai_risk_level',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='kobert_confidence',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='kobert_labels',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='missing_date',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='parsed_cane',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='parsed_glasses',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='parsed_hair_color',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='parsed_height',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='parsed_weight',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='source',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='age_at_missing',
            field=models.IntegerField(blank=True, null=True, verbose_name='당시나이(세)'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='category',
            field=models.CharField(blank=True, default='', help_text='아동, 장애, 치매환자, 가출인 등 (span.info)', max_length=20, verbose_name='분류'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='clothing',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='착의의상'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='crawled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='크롤링일시'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='이미지경로목록'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='msspsn_idntfccd',
            field=models.CharField(default='', help_text='safe182 고유 식별코드 (예: 6096410)', max_length=20, unique=True, verbose_name='실종자식별코드'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='occurred_at',
            field=models.DateField(blank=True, null=True, verbose_name='발생일시'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='occurred_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='발생장소'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='체격'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='current_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='현재나이(세)'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='face_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='얼굴형'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('남자', '남자'), ('여자', '여자')], default='', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='hair_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='두발색상'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='hair_style',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='두발형태'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='height',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='국적'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='진행상태'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='몸무게'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['msspsn_idntfccd'], name='safe182_mis_msspsn__32a2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['occurred_at'], name='safe182_mis_occurre_5ac0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['category'], name='safe182_mis_categor_f90bed_idx'),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['gender'], name='safe182_mis_gender_d7ab0e_idx'),
        ),
        migrations.AlterModelTable(
            name='missingperson',
            table='safe182_missing_person',
        ),
        migrations.DeleteModel(
            name='MissingPersonPhoto',
        ),
    ]
