# Generated by Django 5.2.7 on 2026-03-18 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0028_remove_missingpersonphoto_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tip_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dasibomapp.case')),
            ],
            options={
                'verbose_name': '제보 사진',
                'verbose_name_plural': '제보 사진 목록',
                'db_table': 'dasibomapp_tip_photo',
            },
        ),
    ]
