# Generated by Django 5.2.7 on 2026-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0029_tipphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='etc_spfeatr',
            field=models.TextField(blank=True, default='', verbose_name='추가특징'),
        ),
    ]
