# Generated by Django 5.2.7 on 2026-03-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0030_missingperson_etc_spfeatr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('received', '접수중'), ('reviewing', '확인중'), ('completed', '완료'), ('rejected', '거부')], db_index=True, default='received', max_length=20),
        ),
    ]
