# Generated by Django 5.2.7 on 2026-03-24 06:57

import dasibomapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0032_casereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipphoto',
            name='image',
            field=models.ImageField(upload_to=dasibomapp.models.tip_photo_upload_path),
        ),
    ]
