# Generated by Django 5.2.7 on 2026-04-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0033_alter_tipphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('missing', '실종중'), ('found', '찾음')], default='missing', max_length=20, verbose_name='진행상태'),
        ),
    ]
