# Generated by Django 5.2.7 on 2026-04-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0034_alter_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='source',
            field=models.CharField(choices=[('safe182', 'safe182'), ('user', 'user')], default='safe182', max_length=20),
        ),
    ]
