# Generated by Django 5.2.7 on 2026-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0035_missingperson_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='target_type',
            field=models.CharField(max_length=50),
        ),
    ]
