# Generated by Django 5.2.7 on 2026-04-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0036_alter_log_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedperson',
            name='category',
            field=models.CharField(blank=True, default='', help_text='아동, 장애, 치매환자, 가출인 등', max_length=50, verbose_name='분류'),
        ),
    ]
