# Generated by Django 5.2.7 on 2026-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0037_alter_protectedperson_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedperson',
            name='etc_ai_category',
            field=models.CharField(blank=True, help_text='AI 분류 결과: 신체특징 / 착의외형 / 건강장애 / 기타참고', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='protectedperson',
            name='etc_ai_confidence',
            field=models.FloatField(blank=True, help_text='AI 분류 신뢰도 0.0~1.0', null=True),
        ),
    ]
