# Generated by Django 5.2.7 on 2026-04-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0039_missingperson_etc_ai_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedperson',
            name='source',
            field=models.CharField(choices=[('safe182', 'safe182'), ('user', 'user')], default='safe182', max_length=20),
        ),
    ]
