# Generated by Django 5.2.7 on 2026-05-06 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0040_protectedperson_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='montage',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montages', to='dasibomapp.case'),
        ),
    ]
