# Generated by Django 5.2.7 on 2026-05-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0042_alter_montage_result_img_preventionregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventionphoto',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventionphoto',
            name='validation_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventionphoto',
            name='validation_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preventionphoto',
            name='validation_status',
            field=models.CharField(default='unchecked', help_text='unchecked / valid / warning / invalid / error', max_length=20),
        ),
    ]
