# Generated by Django 5.2.7 on 2026-05-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0043_preventionphoto_is_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventionphoto',
            name='photo_type',
            field=models.CharField(choices=[('face', '얼굴 사진'), ('full_body', '전신 사진'), ('left_side', '왼쪽 측면 사진'), ('right_side', '오른쪽 측면 사진'), ('parent1_face', '부모님 정면 사진 1'), ('parent2_face', '부모님 정면 사진 2')], max_length=30),
        ),
    ]
