# Generated by Django 5.2.7 on 2026-05-12 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0044_alter_preventionphoto_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventionregistration',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventionregistration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventionregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prevention_registrations', to='dasibomapp.person'),
        ),
        migrations.AddField(
            model_name='preventionregistration',
            name='status',
            field=models.CharField(choices=[('received', '접수중'), ('reviewing', '확인중'), ('completed', '등록 완료'), ('rejected', '거절됨')], db_index=True, default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='preventionphoto',
            name='photo_type',
            field=models.CharField(choices=[('face', '등록 대상자 정면 사진'), ('full_body', '등록 대상자 전신 사진'), ('left_side', '등록 대상자 왼쪽 측면 사진'), ('right_side', '등록 대상자 오른쪽 측면 사진'), ('parent1_face', '부모님 정면 사진 1'), ('parent2_face', '부모님 정면 사진 2')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='preventionregistration',
            index=models.Index(fields=['owner'], name='dasibomapp__owner_i_c2fc64_idx'),
        ),
        migrations.AddIndex(
            model_name='preventionregistration',
            index=models.Index(fields=['status'], name='dasibomapp__status_0c35ba_idx'),
        ),
        migrations.AddIndex(
            model_name='preventionregistration',
            index=models.Index(fields=['is_active'], name='dasibomapp__is_acti_f111f6_idx'),
        ),
        migrations.AddIndex(
            model_name='preventionregistration',
            index=models.Index(fields=['created_at'], name='dasibomapp__created_217c05_idx'),
        ),
    ]
