# Generated by Django 5.2.7 on 2026-05-12 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0045_preventionregistration_rejected_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('device_code', models.CharField(db_index=True, help_text='하드웨어에서 전달한 기기 ID', max_length=100)),
                ('lat', models.FloatField(help_text='위도')),
                ('lng', models.FloatField(help_text='경도')),
                ('shared_at', models.DateTimeField(blank=True, help_text='하드웨어에서 전달한 위치 공유 시각', null=True)),
                ('device', models.ForeignKey(blank=True, help_text='DB에 등록된 기기 정보', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to='dasibomapp.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('device_code', models.CharField(db_index=True, help_text='하드웨어에서 전달한 기기 ID', max_length=100)),
                ('reported_at', models.DateTimeField(blank=True, help_text='하드웨어에서 전달한 신고 발생 시각', null=True)),
                ('device', models.ForeignKey(blank=True, help_text='DB에 등록된 기기 정보', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports', to='dasibomapp.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
