# Generated by Django 5.2.7 on 2026-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0047_gpslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipphoto',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
