# Generated by Django 5.2.7 on 2026-05-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0048_missingperson_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='is_ai_generated',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='ai_image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
