# Generated by Django 5.2.7 on 2026-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0049_remove_missingperson_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='etc_ai_segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
