# Generated by Django 5.2.7 on 2026-06-04 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0050_missingperson_etc_ai_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventionregistration',
            name='device_code',
            field=models.CharField(blank=True, help_text='피보호자에게 연결할 GPS/NFC 기기 코드', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventionregistration',
            name='linked_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_prevention_registrations', to='dasibomapp.person'),
        ),
    ]
