# Generated by Django 5.2.7 on 2026-08-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0051_preventionregistration_device_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guardian',
            name='uniq_guardian_ward',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='dasibomapp__person__75003c_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='dasibomapp__status_6e8a7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='dasibomapp__last_si_8c16c3_idx',
        ),
        migrations.AlterField(
            model_name='device',
            name='nfc_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='person',
            field=models.OneToOneField(blank=True, help_text='연결된 피보호자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge', to='dasibomapp.person'),
        ),
        migrations.AlterField(
            model_name='device',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_relations', to='dasibomapp.person'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='ward',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relation', to='dasibomapp.person'),
        ),
    ]
