# Generated by Django 5.2.7 on 2026-08-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0052_remove_guardian_uniq_guardian_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventionregistration',
            name='category',
            field=models.CharField(blank=True, choices=[('010', '정상아동 (18세 미만)'), ('020', '가출인'), ('040', '시설 보호 무연고자'), ('060', '지적장애인'), ('061', '지적장애인 (18세 미만)'), ('062', '지적장애인 (18세 이상)'), ('070', '치매 질환자'), ('080', '불상 (기타)')], default='', help_text='아동, 장애, 치매환자, 가출인 등', max_length=3, verbose_name='분류'),
        ),
    ]
