# Generated by Django 5.2.7 on 2026-08-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0053_preventionregistration_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(db_index=True, max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='guardian',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relations', to='dasibomapp.person'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(fields=('guardian', 'ward'), name='uniq_guardian_ward'),
        ),
        migrations.AddField(
            model_name='gpslocationhistory',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_history', to='dasibomapp.device'),
        ),
        migrations.AddIndex(
            model_name='gpslocationhistory',
            index=models.Index(fields=['device_code', 'timestamp'], name='dasibomapp__device__c96fc5_idx'),
        ),
    ]
