# Generated by Django 5.2.7 on 2026-08-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0054_gpslocationhistory_alter_guardian_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='badge_uid',
            field=models.CharField(blank=True, db_index=True, help_text='키링에 붙은 NFC 스티커 UID (소문자 hex, 구분자 없음)', max_length=32, null=True, unique=True),
        ),
    ]
