# Generated by Django 5.2.7 on 2026-09-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasibomapp', '0055_device_badge_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipphoto',
            options={'verbose_name': '신고/제보 사진', 'verbose_name_plural': '신고/제보 사진 목록'},
        ),
        migrations.AddField(
            model_name='tipphoto',
            name='photo_type',
            field=models.CharField(choices=[('subject', '대상자 사진'), ('parent1_face', '가족 사진 1'), ('parent2_face', '가족 사진 2')], db_index=True, default='subject', help_text='subject=대상자 사진, parent1_face=가족 사진 1, parent2_face=가족 사진 2', max_length=20),
        ),
    ]
