"""
Django settings for dasibom project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv


# ==============================
# 기본 경로 / 환경변수
# ==============================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# ==============================
# 기본 설정
# ==============================

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = ["*"]


# ==============================
# Application definition
# ==============================

INSTALLED_APPS = [
    "daphne",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Cloudinary
    "cloudinary",

    # Third party
    "rest_framework",
    "corsheaders",
    "social_django",
    "django_filters",
    "django_apscheduler",
    "channels",

    # Local
    "dasibomapp",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = "dasibom.urls"


# ==============================
# 인증
# ==============================

AUTHENTICATION_BACKENDS = (
    "social_core.backends.kakao.KakaoOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)


SOCIAL_AUTH_KAKAO_KEY = os.getenv("KAKAO_KEY")

SOCIAL_AUTH_KAKAO_SECRET = ""


# 환경별 변경 가능
# 로컬:
# http://127.0.0.1:8000/oauth/complete/kakao/
#
# Render:
# https://dasibom-m9c3.onrender.com/oauth/complete/kakao/
SOCIAL_AUTH_KAKAO_REDIRECT_URI = os.getenv(
    "KAKAO_REDIRECT_URI",
    "http://127.0.0.1:8000/oauth/complete/kakao/",
)


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# ==============================
# Template
# ==============================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ==============================
# WSGI / ASGI
# ==============================

WSGI_APPLICATION = "dasibom.wsgi.application"

ASGI_APPLICATION = "dasibom.asgi.application"


# ==============================
# CSRF
# ==============================

CSRF_TRUSTED_ORIGINS = [
    "https://dasibom-api.shares.zrok.io",
    "https://dasibom-m9c3.onrender.com",
]


# ==============================
# Database
# ==============================

DB_HOST = os.getenv(
    "DB_HOST",
    "localhost",
)


db_options = {}


# Aiven 같은 외부 MySQL일 때만 SSL 적용
if DB_HOST not in (
    "localhost",
    "127.0.0.1",
):
    ca_path = (
        BASE_DIR
        / "aiven-ca.pem"
    )

    if ca_path.exists():
        db_options = {
            "ssl": {
                "ca": str(ca_path),
            }
        }

DATABASES = {
    "default": {
        "ENGINE": (
            "django.db.backends.mysql"
        ),

        "NAME": os.getenv(
            "DB_NAME"
        ),

        "USER": os.getenv(
            "DB_USER"
        ),

        "PASSWORD": os.getenv(
            "DB_PASSWORD"
        ),

        "HOST": DB_HOST,

        "PORT": os.getenv(
            "DB_PORT",
            "3306",
        ),

        "OPTIONS": db_options,

        # DB 연결을 매 요청마다 새로 만들지 않고
        # 최대 60초 동안 재사용
        "CONN_MAX_AGE": 60,

        # 재사용하기 전에 연결이 살아있는지 확인
        "CONN_HEALTH_CHECKS": True,
    }
}

# ==============================
# Password validation
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ==============================
# DRF / JWT
# ==============================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "dasibomapp.authentication.CustomJWTAuthentication",
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        days=14
    ),

    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=30
    ),

    "BLACKLIST_AFTER_ROTATION": False,

    "ROTATE_REFRESH_TOKENS": False,

    "AUTH_HEADER_TYPES": (
        "Bearer",
    ),
}


# ==============================
# Channels
# ==============================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": (
            "channels.layers."
            "InMemoryChannelLayer"
        ),
    }
}


# ==============================
# Internationalization
# ==============================

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# ==============================
# Static
# ==============================

STATIC_URL = "/static/"

STATIC_ROOT = (
    BASE_DIR
    / "staticfiles"
)


# ==============================
# Media
# ==============================

MEDIA_URL = "/media/"

MEDIA_ROOT = (
    BASE_DIR
    / "media"
)


# --------------------------------
# Media 저장 모드
# --------------------------------
#
# MEDIA_WRITE_MODE:
#   local
#   cloudinary
#   both
#
# MEDIA_READ_MODE:
#   local
#   cloudinary
#
# 현재 추천:
#
# MEDIA_WRITE_MODE=both
# MEDIA_READ_MODE=cloudinary
#
# zrok 복귀 시:
#
# MEDIA_WRITE_MODE=local
# MEDIA_READ_MODE=local
# --------------------------------

MEDIA_WRITE_MODE = os.getenv(
    "MEDIA_WRITE_MODE",
    "local",
).lower()

MEDIA_READ_MODE = os.getenv(
    "MEDIA_READ_MODE",
    "local",
).lower()


# ==============================
# Cloudinary
# ==============================

CLOUDINARY_CLOUD_NAME = os.getenv(
    "CLOUDINARY_CLOUD_NAME"
)

CLOUDINARY_API_KEY = os.getenv(
    "CLOUDINARY_API_KEY"
)

CLOUDINARY_API_SECRET = os.getenv(
    "CLOUDINARY_API_SECRET"
)


# cloudinary 패키지가 사용하는 전역 설정
import cloudinary

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True,
)


# ==============================
# Django Storage
# ==============================

STORAGES = {
    # 우리가 만든 범용 Storage
    "default": {
        "BACKEND": (
            "dasibomapp.storage."
            "UniversalMediaStorage"
        ),
    },

    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles."
            "storage.StaticFilesStorage"
        ),
    },
}


DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ==============================
# SAFE182 / 사고다발지역
# ==============================

SAFE182_RADIUS_KM = 0.3

SAFE182_USER_ID = os.getenv(
    "SAFE182_USER_ID"
)

SAFE182_API_KEY = os.getenv(
    "SAFE182_API_KEY"
)


FREQUENTZONE_API_KEY = os.getenv(
    "FREQUENTZONE_API_KEY"
)

FREQUENTZONE_RADIUS_KM = 1.0


# ==============================
# Cache
# ==============================

CACHES = {
    "default": {
        "BACKEND": (
            "django.core.cache.backends."
            "locmem.LocMemCache"
        ),
    }
}


# ==============================
# 개발/시연용 전화 인증 우회
# ==============================

DEV_SKIP_PHONE_VERIFY = DEBUG


# ==============================
# AI 서버
# ==============================

AI_SERVER_URL = "https://linseed-shine-emcee.ngrok-free.dev"

AI_AGING_API_URL = f"{AI_SERVER_URL}/api/aging"

AI_HEALTH_URL = f"{AI_SERVER_URL}/health"

AI_AGING_TIMEOUT = 300

DEVICE_REGISTER_KEY = os.getenv(
    "DEVICE_REGISTER_KEY",
    ""
)