// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhRavQK0ZWxUn_A6ggfwCkyA7Idhq9G8',
    appId: '1:1039243571508:web:90ce3beea08bd374c23561',
    messagingSenderId: '1039243571508',
    projectId: 'dasibom-auth',
    authDomain: 'dasibom-auth.firebaseapp.com',
    storageBucket: 'dasibom-auth.firebasestorage.app',
    measurementId: 'G-RE2H958Z4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKYymWtawsb-xBzfMxqgXSNq7H4yjzO0',
    appId: '1:1039243571508:android:6e63376a66383c2ac23561',
    messagingSenderId: '1039243571508',
    projectId: 'dasibom-auth',
    storageBucket: 'dasibom-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBECbS6rgstUWXbI88VUn4p5dtxftKZHhE',
    appId: '1:1039243571508:ios:194cbf3676484d51c23561',
    messagingSenderId: '1039243571508',
    projectId: 'dasibom-auth',
    storageBucket: 'dasibom-auth.firebasestorage.app',
    iosBundleId: 'com.example.dasibom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBECbS6rgstUWXbI88VUn4p5dtxftKZHhE',
    appId: '1:1039243571508:ios:194cbf3676484d51c23561',
    messagingSenderId: '1039243571508',
    projectId: 'dasibom-auth',
    storageBucket: 'dasibom-auth.firebasestorage.app',
    iosBundleId: 'com.example.dasibom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANhRavQK0ZWxUn_A6ggfwCkyA7Idhq9G8',
    appId: '1:1039243571508:web:e5bd17d831d59361c23561',
    messagingSenderId: '1039243571508',
    projectId: 'dasibom-auth',
    authDomain: 'dasibom-auth.firebaseapp.com',
    storageBucket: 'dasibom-auth.firebasestorage.app',
    measurementId: 'G-GQD48JC2PM',
  );
}
